version: "3"
services:
  ## POSTGRES DB
  postgres-dto:
    container_name: postgres-dto
    image: postgres
    environment:
      POSTGRES_DB: dto-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-dto:/data/postgres
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always
    networks:
      - test-network


networks:
  test-network: